time:
  window:
    # validation period start time
    start: 2016-08-01 00:00:00
    # validation period end time
    end: 2016-08-31 23:55:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct
  - cross_correlation

# analysis type (base or swingdoor)
analysis:
  - base_analysis
  # - swingdoor-mag
  # - swingdoor-ramp
  # - swingdoor-dur

aggregation:
  - MS
  # - D
  # - H

# power plant capacity. should have same units as reference.Add commentMore actions
# used to normalize average percent bias (bias_pct) and mean average percent error (mae_pct)
# If left blank, will be calculated from the max of the baseline dataset
capacity: 75

# output
output:
  # output folder path
  path: output/pnw/KL2_avg
  # name of the run
  org: KL2_avg
  # save metrics?
  save_metrics: True
  # save figures?
  save_figs: True
  # show figures?
  show_figs: False
  # print results?
  print_results : True
  # print time steps with NaN values?
  print_NaN_values: False

# baseline dataset
base:
  # name of dataset
  name: PNW_KL2
  # data directory
  path: data/PNW_obs_avg/averaged_wind_power_data.KL2.csv
  # name of data processing function
  function: csv_pnw
  # variable name
  var: Value
  # data frequency in minutes
  freq: 5
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  # name of dataset
  - name: WRF Centroid Actual
    # data directory
    path: data/PNW_centr/wind_wrf_centroid.201608.56359.actual.csv
    # name of data processing function
    function: csv_pnw
    # variable name
    var: capacity
    # data frequency in minutes
    freq: 5
    # flag value
    flag: 999
    # number of turbines
    turbines: 50

  # name of dataset
  - name: WRF Centroid A1
    # data directory
    path: data/PNW_centr/wind_wrf_centroid.201608.56359.A1.csv
    # name of data processing function
    function: csv_pnw
    # variable name
    var: capacity
    # data frequency in minutes
    freq: 5
    # flag value
    flag: 999
    # number of turbines
    turbines: 50

  # name of dataset
  - name: WRF Centroid A2
    # data directory
    path: data/PNW_centr/wind_wrf_centroid.201608.56359.A2.csv
    # name of data processing function
    function: csv_pnw
    # variable name
    var: capacity
    # data frequency in minutes
    freq: 5
    # flag value
    flag: 999
    # number of turbines
    turbines: 50

  # name of dataset
  - name: WRF Centroid A3
    # data directory
    path: data/PNW_centr/wind_wrf_centroid.201608.56359.A3.csv
    # name of data processing function
    function: csv_pnw
    # variable name
    var: capacity
    # data frequency in minutes
    freq: 5
    # flag value
    flag: 999
    # number of turbines
    turbines: 50


# reference
reference: 
  # variable name to be displayed
  var: Power
  # variable units
  units: MW