# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 54.9733
  lon: 13.1778

time:
  window:
    # validation period start time
    start: 2020-10-03 23:00:00
    # validation period end time
    end: 2020-10-10 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - nrmse
  - bias
  - bias_pct
  - mae
  - mae_pct
  - mdae
  - mdae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 78.25
  height_units: m

# baseline dataset
base:
  name: baltic2
  # data directory
  path: data/baltic2/
  # name of data processing function
  function: baltic2_xlsx
  # names of variables in data to validate
  var: power
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: power
  # target variable name to be displayed
  target_var: baltic_power
  # data frequency in minutes
  freq: 15
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: p1m
    path: data/submissions/means/
    file: p1_baltic-power.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p1m_power
    freq: 60
  - name: p2m
    # data directory
    path: data/submissions/means/
    # data file
    file: p2_mean_baltic-power.csv
    # name of data processing function
    function: submission_csv
    # names of variables in data to validate
    # not being used in submission_csv
    var: dummy
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: power
    # target variable name to be displayed
    target_var: p2m_power
    # data frequency in minutes
    freq: 60
  - name: p3m
    path: data/submissions/means/
    file: p3_mean_baltic-power.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p3m_power
    freq: 60
  - name: p4m
    path: data/submissions/means/
    file: p4_mean_baltic-power.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p4m_power
    freq: 60
  - name: p5m
    path: data/submissions/means/
    file: p5_mean_baltic-power.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5m_power
    freq: 60
  - name: p6m
    path: data/submissions/means/
    file: p6_baltic-power.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p6m_power
    freq: 60
  - name: allm
    path: data/submissions/means/
    file: orgs_mean_baltic-power.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: allm_power
    freq: 60

# ramps
ramps:
  # all ramps
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 10 hours
  - definition: r_abs_magnitude
    magnitude: 50
    duration: 8 hours
  - definition: r_abs_magnitude
    magnitude: 50
    duration: 6 hours
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 5 hours
  - definition: r_abs_magnitude
    magnitude: 50
    duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 3 hours
  - definition: r_abs_magnitude
    magnitude: 50
    duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 1 hours

  - definition: r_abs_magnitude
    magnitude: 100
    duration: 10 hours
  - definition: r_abs_magnitude
    magnitude: 100
    duration: 8 hours
  - definition: r_abs_magnitude
    magnitude: 100
    duration: 6 hours
  # - definition: r_abs_magnitude
  #   magnitude: 100
  #   duration: 5 hours
  - definition: r_abs_magnitude
    magnitude: 100
    duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 100
  #   duration: 3 hours
  - definition: r_abs_magnitude
    magnitude: 100
    duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 100
  #   duration: 1 hours

  - definition: r_abs_magnitude
    magnitude: 150
    duration: 12 hours
  - definition: r_abs_magnitude
    magnitude: 150
    duration: 10 hours
  - definition: r_abs_magnitude
    magnitude: 150
    duration: 8 hours
  # - definition: r_abs_magnitude
  #   magnitude: 150
  #   duration: 7 hours
  - definition: r_abs_magnitude
    magnitude: 150
    duration: 6 hours
  # - definition: r_abs_magnitude
  #   magnitude: 150
  #   duration: 5 hours
  - definition: r_abs_magnitude
    magnitude: 150
    duration: 4 hours

  - definition: r_abs_magnitude
    magnitude: 200
    duration: 12 hours
  - definition: r_abs_magnitude
    magnitude: 200
    duration: 10 hours
  # - definition: r_abs_magnitude
  #   magnitude: 200
  #   duration: 9 hours
  - definition: r_abs_magnitude
    magnitude: 200
    duration: 8 hours
  # - definition: r_abs_magnitude
  #   magnitude: 200
  #   duration: 7 hours
  - definition: r_abs_magnitude
    magnitude: 200
    duration: 6 hours
  # - definition: r_abs_magnitude
  #   magnitude: 200
  #   duration: 5 hours
  - definition: r_abs_magnitude
    magnitude: 200
    duration: 4 hours

  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 10 hours
  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 9 hours
  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 8 hours
  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 7 hours
  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 6 hours
  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 5 hours
  # - definition: r_abs_magnitude
  #   magnitude: 250
  #   duration: 4 hours

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: power
  # variable units
  units: MW

# writing output file
output:
  writing: True
  # path to write file
  path: output/60min/baltic-power/allmeans
  # organization
  org: allmeans
  # output file format
  format: csv