# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 54.9733
  lon: 13.1778

time:
  window:
    # validation period start time
    start: 2020-10-03 23:00:00
    # validation period end time
    end: 2020-10-10 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - nrmse
  - bias
  - bias_pct
  - mae
  - mae_pct
  - mdae
  - mdae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 78.25
  height_units: m

# baseline dataset
base:
  name: baltic2
  # data directory
  path: data/baltic2/
  # name of data processing function
  function: baltic2_xlsx
  # names of variables in data to validate
  var: power
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: power
  # target variable name to be displayed
  target_var: baltic_power
  # data frequency in minutes
  freq: 15
  # flag value
  flag: 999

# ramps
ramps:
  # all ramps
  - definition: r_abs_magnitude
    magnitude: 50
    duration: 6 hours
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 5 hours
  # - definition: r_abs_magnitude
  #   # in units of base var
  #   magnitude: 50
  #   # must be a Timedelta duration argument, with numeric and units
  #   duration: 4 hours
  #   # plotting: True
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 50
  #   duration: 1 hours

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: power
  # variable units
  units: MW

# writing output file
output:
  writing: True
  # path to write file
  path: output/60min/baltic-power
  # organization
  org: p5
  # output file format
  format: csv

# data input to be compared with the baseline dataset
comp:
  - name: p5-1
    # data directory
    path: output/60min/baltic/p5_derived_power/
    # data file
    file: derived_power_p5-1.csv
    # name of data processing function
    function: submission_csv
    # names of variables in data to validate
    # not being used in submission_csv
    var: dummy
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: power
    # target variable name to be displayed
    target_var: p5-1_power
    # data frequency in minutes
    freq: 60
  - name: p5-2
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-2.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-2_power
    freq: 60
  - name: p5-3
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-3.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-3_power
    freq: 60
  - name: p5-4
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-4.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-4_power
    freq: 60
  - name: p5-5
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-5.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-5_power
    freq: 60
  - name: p5-6
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-6.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-6_power
    freq: 60
  - name: p5-7
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-7.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-7_power
    freq: 60
  - name: p5-8
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-8.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-8_power
    freq: 60
  - name: p5-9
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-9.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-9_power
    freq: 60
  - name: p5-10
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-10.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-10_power
    freq: 60
  #
  - name: p5-11
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-11.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-11_power
    freq: 60
  - name: p5-12
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-12.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-12_power
    freq: 60
  - name: p5-13
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-13.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-13_power
    freq: 60
  - name: p5-14
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-14.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-14_power
    freq: 60
  - name: p5-15
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-15.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-15_power
    freq: 60
  - name: p5-16
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-16.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-16_power
    freq: 60
  - name: p5-17
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-17.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-17_power
    freq: 60
  - name: p5-18
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-18.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-18_power
    freq: 60
  - name: p5-19
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-19.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-19_power
    freq: 60
  - name: p5-20
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-20.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-20_power
    freq: 60
  #
  - name: p5-21
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-21.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-21_power
    freq: 60
  - name: p5-22
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-22.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-22_power
    freq: 60
  - name: p5-23
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-23.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-23_power
    freq: 60
  - name: p5-24
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-24.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-24_power
    freq: 60
  - name: p5-25
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-25.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-25_power
    freq: 60
  - name: p5-26
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-26.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-26_power
    freq: 60
  - name: p5-27
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-27.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-27_power
    freq: 60
  - name: p5-28
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-28.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-28_power
    freq: 60
  - name: p5-29
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-29.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-29_power
    freq: 60
  - name: p5-30
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-30.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-30_power
    freq: 60
  #
  - name: p5-31
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-31.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-31_power
    freq: 60
  - name: p5-32
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-32.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-32_power
    freq: 60
  - name: p5-33
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-33.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-33_power
    freq: 60
  - name: p5-34
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-34.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-34_power
    freq: 60
  - name: p5-35
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-35.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-35_power
    freq: 60
  - name: p5-36
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-36.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-36_power
    freq: 60
  - name: p5-37
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-37.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-37_power
    freq: 60
  - name: p5-38
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-38.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-38_power
    freq: 60
  - name: p5-39
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-39.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-39_power
    freq: 60
  - name: p5-40
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-40.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-40_power
    freq: 60
  #
  - name: p5-41
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-41.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-41_power
    freq: 60
  - name: p5-42
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-42.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-42_power
    freq: 60
  - name: p5-43
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-43.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-43_power
    freq: 60
  - name: p5-44
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-44.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-44_power
    freq: 60
  - name: p5-45
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-45.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-45_power
    freq: 60
  - name: p5-46
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-46.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-46_power
    freq: 60
  - name: p5-47
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-47.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-47_power
    freq: 60
  - name: p5-48
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-48.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-48_power
    freq: 60
  - name: p5-49
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-49.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-49_power
    freq: 60
  - name: p5-50
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-50.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-50_power
    freq: 60
  #
  - name: p5-51
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-51.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-51_power
    freq: 60
  - name: p5-52
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-52.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-52_power
    freq: 60
  - name: p5-53
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-53.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-53_power
    freq: 60
  - name: p5-54
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-54.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-54_power
    freq: 60
  - name: p5-55
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-55.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-55_power
    freq: 60
  - name: p5-56
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-56.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-56_power
    freq: 60
  - name: p5-57
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-57.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-57_power
    freq: 60
  - name: p5-58
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-58.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-58_power
    freq: 60
  - name: p5-59
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-59.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-59_power
    freq: 60
  - name: p5-60
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-60.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-60_power
    freq: 60
  #
  - name: p5-61
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-61.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-61_power
    freq: 60
  - name: p5-62
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-62.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-62_power
    freq: 60
  - name: p5-63
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-63.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-63_power
    freq: 60
  - name: p5-64
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-64.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-64_power
    freq: 60
  - name: p5-65
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-65.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-65_power
    freq: 60
  - name: p5-66
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-66.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-66_power
    freq: 60
  - name: p5-67
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-67.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-67_power
    freq: 60
  - name: p5-68
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-68.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-68_power
    freq: 60
  - name: p5-69
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-69.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-69_power
    freq: 60
  - name: p5-70
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-70.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-70_power
    freq: 60
#
  - name: p5-71
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-71.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-71_power
    freq: 60
  - name: p5-72
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-72.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-72_power
    freq: 60
  - name: p5-73
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-73.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-73_power
    freq: 60
  - name: p5-74
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-74.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-74_power
    freq: 60
  - name: p5-75
    path: output/60min/baltic/p5_derived_power/
    file: derived_power_p5-75.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: p5-75_power
    freq: 60
