
time:
  window:
    # validation period start time
    start: 2018-01-01 12:00:00
    # validation period end time
    end: 2019-01-01 12:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct

# output
output:
  # output folder path
  path: output
  # name of the run
  org: palouse
  # save metrics?
  save_metrics: True
  # save figures?
  save_figs: False
  # show figures?
  show_figs: True
  # print results?
  print_results : False

# baseline dataset
base:
  # name of dataset
  name: EIA 930
  # data directory
  path: data/pluswind/EIA_930.csv
  # name of data processing function
  function: csv
  # variable name
  var: power
  # data frequency in minutes
  freq: 60
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  # name of dataset
  - name: NREL 2018 (2032 ADS) - HRRR
    # data directory
    path: data/pluswind/nrel_2018_(2032 ADS)-HRRR.csv
    # name of data processing function
    function: csv
    # variable name
    var: power
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999

  # name of dataset
  - name: PLUSWIND HRRR
    # data directory
    path: data/pluswind/plant.c0.2018.57530.csv
    # name of data processing function
    function: csv
    # variable name
    var: power
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999


# reference
reference: 
  # variable name to be displayed
  var: Power
  # variable units
  units: MW

