
time:
  window:
    # validation period start time
    start: 2018-01-01 12:00:00
    # validation period end time
    end: 2019-01-01 12:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct
  - cross_correlation

# power plant capacity. should have same units as reference.
# used to normalize average percent bias (bias_pct) and mean average percent error (mae_pct)
# If left blank, will be calculated from the max of the baseline dataset
capacity: 104

analysis:
  - base_analysis
  - swingdoor-mag
  - swingdoor-ramp
  - swingdoor-dur



aggregation:
  - MS
  - D
  - H

# output
output:
  # output folder path
  path: output
  # name of the run
  org: test
  # save metrics?
  save_metrics: True
  # save figures?
  save_figs: False
  # show figures?
  show_figs: False

# baseline dataset
base:
  # name of dataset
  name: EIA 930
  # data directory
  path: data/example/EIA-930.csv
  # name of data processing function
  function: csv
  # variable name
  var: power
  # data frequency in minutes
  freq: 60
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  # name of dataset
  - name: NWPDB HRRR
    # data directory
    path: data/example/nwpdb-HRRR.csv
    # name of data processing function
    function: csv
    # variable name
    var: power
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999

  # name of dataset
  - name: PLUSWIND HRRR
    # data directory
    path: data/example/pluswind-HRRR.csv
    # name of data processing function
    function: csv
    # variable name
    var: power
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999


# reference
reference:
  # variable name to be displayed
  var: Power
  # variable units
  units: MW