# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 55.006928
  lon: 13.154189

time:
  window:
    # validation period start time
    start: 2020-10-04 00:00:00
    # validation period end time
    end: 2020-10-11 00:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse

levels: 
  # height level of validation above ground level
  height_agl: 
    - 82
  height_units: m

# baseline dataset
base:
  name: fino2-82-ws
  # data directory
  path: data/fino2/cup-ws-82
  # name of data processing function
  function: fino2_dat
  # names of variables in data to validate
  var: Value
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: ws
  # data frequency in minutes
  freq: 10

# data input to be compared with the baseline dataset
comp:
  - name: fino2-52-ws
    # data directory
    path: data/fino2/cup-ws-52
    # name of data processing function
    function: fino2_dat
    # names of variables in data to validate
    var: Value
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: ws
    # data frequency in minutes
    freq: 10
  - name: fino2-102-ws
    # data directory
    path: data/fino2/cup-ws-102
    # name of data processing function
    function: fino2_dat
    # names of variables in data to validate
    var: Value
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: ws
    # data frequency in minutes
    freq: 10

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: wind speed
  # variable units
  units: ms-1