# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 45.57451
  lon: -120.74734

# Specify which balancing authority to compare
BA: AVA

time:
  window:
    # validation period start time
    start: 2018-07-01 00:00:00
    # validation period end time
    end: 2018-12-31 23:00:00
# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct


# baseline dataset
base:
  name: EIA_930
  # data directory
  path: data/csv/EIA_1h.csv
  # name of data processing function
  function: ba_power_csv
  # names of variables in data to validate
  var: power
  # nature of variable
  nature: power
  # target variable name to be displayed
  target_var: EIA_930
  # data frequency in minutes
  freq: 60
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: HRRR
    # data directory
    path: data/csv/NREL_1h.csv
    # name of data processing function
    function: ba_power_csv
    # names of variables in data to validate
    var: power
    # nature of variable
    nature: power
    # target variable name to be displayed
    target_var: HRRR
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999

  - name: New_WTK
    # data directory
    path: data/csv/NREL_1h_downsampled_from_5min.csv
    # name of data processing function
    function: ba_power_csv
    # names of variables in data to validate
    var: power
    # nature of variable
    nature: power
    # target variable name to be displayed
    target_var: New_WTK
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999


# reference
reference: 
  # variable name to be displayed
  var: Power
  # variable units
  units: MW