# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 54.9733
  lon: 13.1778

time:
  window:
    # validation period start time
    start: 2020-10-03 23:00:00
    # validation period end time
    end: 2020-10-10 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 78.25
  height_units: m

# baseline dataset
base:
  name: baltic2
  # data directory
  path: data/baltic2/
  # name of data processing function
  function: baltic2_xlsx
  # names of variables in data to validate
  var: power
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: power
  # target variable name to be displayed
  target_var: baltic_power
  # data frequency in minutes
  freq: 10
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: dw0321
    # data directory
    path: data/submissions/Deutscher_Wetterdienst/
    # data file
    file: benchmark_ICON2020100321_eucase_baltic2.csv
    # name of data processing function
    function: submission_csv
    # names of variables in data to validate
    # not being used in submission_csv
    var: dummy
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: power
    # target variable name to be displayed
    target_var: dw0321_power
    # data frequency in minutes
    freq: 30
    # flag value
    flag: 999
  - name: dw0400
    path: data/submissions/Deutscher_Wetterdienst/
    file: benchmark_ICON2020100400_eucase_baltic2.csv
    function: submission_csv
    var: dummy
    nature: power
    target_var: dw0400_power
    freq: 30

# ramps
ramps:
  # all ramps
  - definition: r_abs_magnitude
    # in units of base var
    magnitude: 100
    # must be a Timedelta duration argument, with numeric and units
    duration: 4 hours
  - definition: r_abs_magnitude
    magnitude: 150
    duration: 4 hours
  # up ramps
  - definition: r_magnitude
    magnitude: 100
    duration: 4 hours
  - definition: r_magnitude
    magnitude: 150
    duration: 4 hours
  # down ramps
  - definition: r_magnitude
    magnitude: -100
    duration: 4 hours
  - definition: r_magnitude
    magnitude: -150
    duration: 4 hours

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: power
  # variable units
  units: MW

# writing output file
output:
  writing: False
  # path to write file
  path: output/baltic-p
  # organization
  org: dw
  # output file format
  format: csv