# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 54.9733
  lon: 13.1778

time:
  window:
    # validation period start time
    start: 2020-10-03 23:00:00
    # validation period end time
    end: 2020-10-10 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 78.25
  height_units: m

# baseline dataset
base:
  name: baltic2
  # data directory
  path: data/baltic2/
  # name of data processing function
  function: baltic2_xlsx
  # names of variables in data to validate
  var: ws
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: ws
  # target variable name to be displayed
  target_var: baltic_ws
  # data frequency in minutes
  freq: 15
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: meso1
    # data directory
    path: data/submissions/Meso/eu/
    # data file
    file: MESO_fcst1_BAL2_2020100318_EU_case.csv
    # name of data processing function
    function: submission_csv
    # names of variables in data to validate
    # not being used in submission_csv
    var: dummy
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: ws
    # target variable name to be displayed
    target_var: meso1_ws
    # data frequency in minutes
    freq: 30
  - name: meso2
    path: data/submissions/Meso/eu/
    file: MESO_fcst2_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso2_ws
    freq: 30
  - name: meso3
    path: data/submissions/Meso/eu/
    file: MESO_fcst3_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso3_ws
    freq: 30
  - name: meso4
    path: data/submissions/Meso/eu/
    file: MESO_fcst4_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso4_ws
    freq: 30
  - name: meso5
    path: data/submissions/Meso/eu/
    file: MESO_fcst5_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso5_ws
    freq: 30
  - name: meso6
    path: data/submissions/Meso/eu/
    file: MESO_fcst6_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso6_ws
    freq: 30
  - name: meso7
    path: data/submissions/Meso/eu/
    file: MESO_fcst7_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso7_ws
    freq: 30
  - name: meso8
    path: data/submissions/Meso/eu/
    file: MESO_fcst8_BAL2_2020100318_EU_case.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: meso8_ws
    freq: 30

# ramps
ramps:
  # all ramps
  - definition: r_abs_magnitude
    # in units of base var
    magnitude: 2
    # must be a Timedelta duration argument, with numeric and units
    duration: 4 hours
  - definition: r_abs_magnitude
    magnitude: 3
    duration: 4 hours
  # up ramps
  - definition: r_magnitude
    magnitude: 2
    duration: 4 hours
  - definition: r_magnitude
    magnitude: 3
    duration: 4 hours
  # down ramps
  - definition: r_magnitude
    magnitude: -2
    duration: 4 hours
  - definition: r_magnitude
    magnitude: -3
    duration: 4 hours

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: wind speed
  # variable units
  units: ms-1

# writing output file
output:
  writing: True
  # path to write file
  path: output/baltic
  # organization
  org: meso
  # output file format
  format: csv