# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 55.006928
  lon: 13.154189

time:
  window:
    # validation period start time
    start: 2020-10-03 23:00:00
    # validation period end time
    end: 2020-10-10 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - nrmse
  - bias
  - bias_pct
  - mae
  - mae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 62
    - 72
    - 82
    - 92
  height_units: m

# baseline dataset
base:
  name: fino2
  # data directory
  path: data/fino2/cup-ws
  # name of data processing function
  function: fino2_dats
  # names of variables in data to validate
  var: Value
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: ws
  # target variable name to be displayed
  target_var: fino_ws
  # data frequency in minutes
  freq: 10
  # flag value
  flag: 999

# ramps
ramps:
  # all ramps
  - definition: r_abs_magnitude
    # in units of base var
    magnitude: 2
    # must be a Timedelta duration argument, with numeric and units
    duration: 4 hours
  - definition: r_abs_magnitude
    magnitude: 3
    duration: 4 hours
  # up ramps
  - definition: r_magnitude
    magnitude: 2
    duration: 4 hours
  - definition: r_magnitude
    magnitude: 3
    duration: 4 hours
  # down ramps
  - definition: r_magnitude
    magnitude: -2
    duration: 4 hours
  - definition: r_magnitude
    magnitude: -3
    duration: 4 hours

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: wind speed
  # variable units
  units: ms-1

# writing output file
output:
  writing: True
  # path to write file
  path: output/fino
  # organization
  org: weprog
  # output file format
  format: csv

# data input to be compared with the baseline dataset
comp:
  - name: weprog1
    # data directory
    path: data/submissions/WEPROG/
    # data file
    file: weprog_FINO2_m1.csv
    # name of data processing function
    function: submission_csv
    # names of variables in data to validate
    # not being used in submission_csv
    var: dummy
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: ws
    # target variable name to be displayed
    target_var: weprog1_ws
    # data frequency in minutes
    freq: 60
  - name: weprog2
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m2.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog2_ws
    freq: 60
  - name: weprog3
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m3.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog3_ws
    freq: 60
  - name: weprog4
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m4.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog4_ws
    freq: 60
  - name: weprog5
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m5.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog5_ws
    freq: 60
  - name: weprog6
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m6.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog6_ws
    freq: 60
  - name: weprog7
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m7.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog7_ws
    freq: 60
  - name: weprog8
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m8.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog8_ws
    freq: 60
  - name: weprog9
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m9.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog9_ws
    freq: 60
  - name: weprog10
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m10.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog10_ws
    freq: 60
  #
  - name: weprog11
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m11.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog11_ws
    freq: 60
  - name: weprog12
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m12.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog12_ws
    freq: 60
  - name: weprog13
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m13.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog13_ws
    freq: 60
  - name: weprog14
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m14.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog14_ws
    freq: 60
  - name: weprog15
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m15.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog15_ws
    freq: 60
  - name: weprog16
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m16.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog16_ws
    freq: 60
  - name: weprog17
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m17.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog17_ws
    freq: 60
  - name: weprog18
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m18.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog18_ws
    freq: 60
  - name: weprog19
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m19.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog19_ws
    freq: 60
  - name: weprog20
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m20.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog20_ws
    freq: 60
  #
  - name: weprog21
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m21.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog21_ws
    freq: 60
  - name: weprog22
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m22.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog22_ws
    freq: 60
  - name: weprog23
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m23.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog23_ws
    freq: 60
  - name: weprog24
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m24.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog24_ws
    freq: 60
  - name: weprog25
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m25.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog25_ws
    freq: 60
  - name: weprog26
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m26.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog26_ws
    freq: 60
  - name: weprog27
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m27.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog27_ws
    freq: 60
  - name: weprog28
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m28.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog28_ws
    freq: 60
  - name: weprog29
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m29.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog29_ws
    freq: 60
  - name: weprog30
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m30.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog30_ws
    freq: 60
  #
  - name: weprog31
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m31.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog31_ws
    freq: 60
  - name: weprog32
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m32.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog32_ws
    freq: 60
  - name: weprog33
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m33.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog33_ws
    freq: 60
  - name: weprog34
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m34.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog34_ws
    freq: 60
  - name: weprog35
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m35.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog35_ws
    freq: 60
  - name: weprog36
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m36.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog36_ws
    freq: 60
  - name: weprog37
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m37.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog37_ws
    freq: 60
  - name: weprog38
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m38.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog38_ws
    freq: 60
  - name: weprog39
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m39.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog39_ws
    freq: 60
  - name: weprog40
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m40.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog40_ws
    freq: 60
  #
  - name: weprog41
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m41.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog41_ws
    freq: 60
  - name: weprog42
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m42.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog42_ws
    freq: 60
  - name: weprog43
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m43.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog43_ws
    freq: 60
  - name: weprog44
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m44.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog44_ws
    freq: 60
  - name: weprog45
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m45.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog45_ws
    freq: 60
  - name: weprog46
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m46.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog46_ws
    freq: 60
  - name: weprog47
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m47.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog47_ws
    freq: 60
  - name: weprog48
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m48.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog48_ws
    freq: 60
  - name: weprog49
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m49.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog49_ws
    freq: 60
  - name: weprog50
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m50.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog50_ws
    freq: 60
  #
  - name: weprog51
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m51.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog51_ws
    freq: 60
  - name: weprog52
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m52.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog52_ws
    freq: 60
  - name: weprog53
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m53.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog53_ws
    freq: 60
  - name: weprog54
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m54.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog54_ws
    freq: 60
  - name: weprog55
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m55.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog55_ws
    freq: 60
  - name: weprog56
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m56.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog56_ws
    freq: 60
  - name: weprog57
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m57.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog57_ws
    freq: 60
  - name: weprog58
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m58.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog58_ws
    freq: 60
  - name: weprog59
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m59.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog59_ws
    freq: 60
  - name: weprog60
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m60.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog60_ws
    freq: 60
  #
  - name: weprog61
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m61.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog61_ws
    freq: 60
  - name: weprog62
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m62.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog62_ws
    freq: 60
  - name: weprog63
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m63.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog63_ws
    freq: 60
  - name: weprog64
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m64.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog64_ws
    freq: 60
  - name: weprog65
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m65.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog65_ws
    freq: 60
  - name: weprog66
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m66.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog66_ws
    freq: 60
  - name: weprog67
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m67.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog67_ws
    freq: 60
  - name: weprog68
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m68.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog68_ws
    freq: 60
  - name: weprog69
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m69.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog69_ws
    freq: 60
  - name: weprog70
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m70.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog70_ws
    freq: 60
#
  - name: weprog71
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m71.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog71_ws
    freq: 60
  - name: weprog72
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m72.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog72_ws
    freq: 60
  - name: weprog73
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m73.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog73_ws
    freq: 60
  - name: weprog74
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m74.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog74_ws
    freq: 60
  - name: weprog75
    path: data/submissions/WEPROG/
    file: weprog_FINO2_m75.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: weprog75_ws
    freq: 60
