
time:
  window:
    # validation period start time
    start: 2016-01-01 12:00:00
    # validation period end time
    end: 2017-01-01 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - bias
  - bias_pct
  - mae
  - mae_pct
  - swingdoor

# output
output:
  # output folder path
  path: output
  # name of the run
  org: test
  # save metrics?
  save_metrics: True
  # save figures?
  save_figs: False
  # show figures?
  show_figs: False
  # print results?
  print_results : False

# baseline dataset
base:
  # name of dataset
  name: Observed
  # data directory
  path: data/obs/clean_csv_lidar_z01.nc.csv
  # name of data processing function
  function: csv
  # variable name
  var: wind_speed
  # data frequency in minutes
  freq: 60
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  # name of dataset
  - name: pnnl_2km
    # data directory
    path: data/2km_pnnl/clean_pnnl_2km_0.0.csv
    # name of data processing function
    function: csv
    # variable name
    var: wind_speed
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999

  # name of dataset
  - name: pnnl_2km_d01
    # data directory
    path: data/2km_pnnl_d01/clean_pnnl_2km_d01_0.0.csv
    # name of data processing function
    function: csv
    # variable name
    var: wind_speed
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999

  # name of dataset
  - name: wtk_4km
    # data directory
    path: data/4km_wtk/clean_4km_wtk_0.0.csv
    # name of data processing function
    function: csv
    # variable name
    var: wind_speed
    # data frequency in minutes
    freq: 60
    # flag value
    flag: 999


# reference
reference: 
  # variable name to be displayed
  var: Wind Speed
  # variable units
  units: ms-1

