# validation location
location: 
  # latitude and longitude in degrees
  # should be the same location as baseline dataset
  lat: 55.006928
  lon: 13.154189

time:
  window:
    # validation period start time
    start: 2020-10-03 22:30:00
    # validation period end time
    end: 2020-10-10 23:00:00

# validation metrics to be calculated and plotted
metrics:
  - rmse
  - crmse
  - nrmse
  - bias
  - bias_pct
  - mae
  - mae_pct
  - mdae
  - mdae_pct

levels: 
  # height level of validation above ground level
  height_agl: 
    - 62
    - 72
    - 82
    - 92
  height_units: m

# baseline dataset
base:
  name: fino2
  # data directory
  path: data/fino2/cup-ws
  # name of data processing function
  function: fino2_dats
  # names of variables in data to validate
  var: Value
  # nature of variable
  # ws: wind speed -- run power curve functions
  nature: ws
  # target variable name to be displayed
  target_var: fino_ws
  # data frequency in minutes
  freq: 10
  # flag value
  flag: 999

# data input to be compared with the baseline dataset
comp:
  - name: p1m
    path: data/submissions/means/
    file: p1_fino.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: p1m_ws
    freq: 60
  - name: p2m
    # data directory
    path: data/submissions/means/
    # data file
    file: p2_mean_fino.csv
    # name of data processing function
    function: submission_csv
    # names of variables in data to validate
    # not being used in submission_csv
    var: dummy
    # nature of variable
    # ws: wind speed -- run power curve functions
    nature: ws
    # target variable name to be displayed
    target_var: p2m_ws
    # data frequency in minutes
    freq: 60
  - name: p3m
    path: data/submissions/means/
    file: p3_mean_fino.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: p3m_ws
    freq: 60
  - name: p4m
    path: data/submissions/means/
    file: p4_mean_fino.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: p4m_ws
    freq: 60
  - name: p5m
    path: data/submissions/means/
    file: p5_mean_fino.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: p5m_ws
    freq: 60
  - name: p6m
    path: data/submissions/means/
    file: p6_fino.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: p6m_ws
    freq: 60
  - name: allm
    path: data/submissions/means/
    file: orgs_mean_fino.csv
    function: submission_csv
    var: dummy
    nature: ws
    target_var: allm_ws
    freq: 60

# ramps
ramps:

# all ramps
  # - definition: r_abs_magnitude
  #   # in units of base var
  #   magnitude: 2
  #   # must be a Timedelta duration argument, with numeric and units
  #   duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 3
  #   duration: 4 hours
  - definition: r_abs_magnitude
    magnitude: 4
    duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 5
  #   duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 6
  #   duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 7
  #   duration: 4 hours
  # - definition: r_abs_magnitude
  #   magnitude: 8
  #   duration: 4 hours

  # - definition: r_abs_magnitude
  #   magnitude: 2
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 3
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 4
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 5
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 6
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 7
  #   duration: 3 hours
  # - definition: r_abs_magnitude
  #   magnitude: 8
  #   duration: 3 hours

  # - definition: r_abs_magnitude
  #   magnitude: 2
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 3
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 4
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 5
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 6
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 7
  #   duration: 2 hours
  # - definition: r_abs_magnitude
  #   magnitude: 8
  #   duration: 2 hours

  # - definition: r_abs_magnitude
  #   magnitude: 2
  #   duration: 1 hours
  # - definition: r_abs_magnitude
  #   magnitude: 3
  #   duration: 1 hours
  # - definition: r_abs_magnitude
  #   magnitude: 4
  #   duration: 1 hours
  # - definition: r_abs_magnitude
  #   magnitude: 5
  #   duration: 1 hours
  # - definition: r_abs_magnitude
  #   magnitude: 6
  #   duration: 1 hours
  # - definition: r_abs_magnitude
  #   magnitude: 7
  #   duration: 1 hours
  # - definition: r_abs_magnitude
  #   magnitude: 8
  #   duration: 1 hours

  # - definition: r_abs_change_rate
  #   percent: 40
  #   rated: 14
  #   duration: 4 hours

# power curve
power_curve: 
  # power curve csv data location
  path: data/power_curve
  # power curve csv name
  file: 2018COE_Market_Average_2.4MW_116.csv
  # name of data processing function
  function: pc_csv
  # wind speed column name in data file
  ws: Wind Speed [m/s]
  # power column name in data file
  power: Power [kW]
  # hub height above ground level
  hub_height: 80

# reference
reference: 
  # variable name to be displayed
  var: wind speed
  # variable units
  units: ms-1

# writing output file
output:
  writing: True
  # path to write file
  path: output/60min/fino/allmeans
  # organization
  org: allmeans
  # output file format
  format: csv